version: '3'

services:
  web:
    build: .
    env_file:
     - ./.env
    command: sh docker-entrypoint.sh
    container_name: web
    volumes:
      - .:/app
      - ./static:/app/static
    ports:
      - "80:4000"
    # depends_on:
    #   - nginx
  # nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   restart: always
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx/sites-available:/etc/nginx/conf.d
  # db:
  #   image: postgres
  #   container_name: Postgres
  #   volumes:
  #     - ./db_data:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_DB: tenlines
  #     # POSTGRES_USER: tenlines
  #     POSTGRES_PASSWORD: sergtsop

# volumes:
#   db_data:
#     driver: local